welcome.message: Hello, this is my test task
error.message: All fields are required!
spring:
  datasource:
    driverClass: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb
    user: SA
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        default_schema: public

