CREATE TABLE CLIENT(
  ID INTEGER PRIMARY KEY,
  LOGIN VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  FULLNAME VARCHAR (64) NOT NULL,
  SEX CHAR NOT NULL
);

CREATE SEQUENCE CLIENTS_SEQ_ID START WITH 1;

